-- Feature 3: log a set.

-- Shared, ready-made list. Users pick from it; they don't add their own (yet).
create table exercises (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique,
  muscle_group text not null
);

create table sets (
  -- Generated by the client, so a retry after bad signal can't double-log
  -- (inserts use ON CONFLICT DO NOTHING), and offline sync can come later.
  id           uuid primary key,
  user_id      text not null,  -- Clerk user ID
  exercise_id  uuid not null references exercises (id),
  weight       numeric(6, 2) not null check (weight >= 0 and weight <= 2000),
  reps         integer not null check (reps between 1 and 100),
  performed_at timestamptz not null default now()
);

comment on column sets.weight is 'Pounds. Add a unit column (default lb) when kg users arrive.';

-- Serves "today's sets", "last set for this exercise", and per-exercise history.
create index sets_user_exercise_time on sets (user_id, exercise_id, performed_at desc);

insert into exercises (name, muscle_group) values
  ('Bench Press',            'Chest'),
  ('Incline Bench Press',    'Chest'),
  ('Dumbbell Bench Press',   'Chest'),
  ('Back Squat',             'Legs'),
  ('Romanian Deadlift',      'Legs'),
  ('Leg Press',              'Legs'),
  ('Leg Curl',               'Legs'),
  ('Leg Extension',          'Legs'),
  ('Deadlift',               'Back'),
  ('Barbell Row',            'Back'),
  ('Pull-Up',                'Back'),
  ('Lat Pulldown',           'Back'),
  ('Seated Cable Row',       'Back'),
  ('Overhead Press',         'Shoulders'),
  ('Lateral Raise',          'Shoulders'),
  ('Barbell Curl',           'Arms'),
  ('Tricep Pushdown',        'Arms');
